filebeat.inputs:
    - type: log
      paths:
      - '/var/lib/docker/containers/*/*.log'
      json.message_key: log
      json.keys_under_root: true
      processors:
      - add_docker_metadata: ~
    output.elasticsearch:
      hosts: ["localhost:9200"]